### ISSUE TITLE
Improve data flow between Cache Tracker and Tracker InGamePanel

### ISSUE THREAD

**Issue by ollyau** [StevenFrost/SimCache#45]
Primary changes:

- [x] Clean up the current `CacheTracker::UpdateTrackerState` function
- [x] Rename `TrackerState` enum to `RangeAnnulus`
- [x] Rename `TrackerStateUpdatedEvent` to `RangeAnnulusChangedEvent`
- [x] Add separate UI events (for things going to the view event dispatcher, eventually used by the HTML/JS InGamePanel)
    - `UIRangeAnnulusChangedEvent` (corresponding to `RangeAnnulusChangedEvent`) -- contains _only_ the `RangeAnnulus` enum value
    - `UITrackedCacheChangedEvent` (corresponding to `TrackedCacheChangedEvent`) -- contains the _full state_ for the range annulus tracker InGamePanel (currently this means (1) the cache name and (2) the `RangeAnnulus` enum value)
- [x] Update the tracker view model to send the two aforementioned UI events to the view event dispatcher as appropriate (this may require adding dependencies on the cache data store, and possibly the aircraft tracker depending on the implementation)
